### ISSUE TITLE
Integrate RSS reader

### ISSUE THREAD

**Issue by bricefriha** [bricefriha/CustardApi#5]
## Description
I'm quite unsatisfied with SyndicationFeed to read and use RSS feeds, since the issues I had with the Ares project (Xamarin Forms). I truly believe this would be quite interesting to integrate an RSS parser in Custard.

## Tasks

- [ ]  Convert RSS to a model
- [ ]  Give the ability to convert an RSS feed to a JSON string
- [ ]  Give the ability to deeply search an image (this one shouldn't be mandatory, a parameter in the parse method will activate it)
- [ ]  Write the unit tests
